### ISSUE TITLE
Browser lang redirect should be removed

### ISSUE THREAD

**Issue by gemanepa** [MinaProtocol/docs#13]
![docs-minaprotocol-redirect-bug](https://user-images.githubusercontent.com/36349751/115135835-eef68480-9ff1-11eb-9b23-a7046dd7f5a9.gif)

From an UX perspective I think the unsolicited language switch from English to browser-based lang when being redirected to the docs subdomain should be removed. Redirecting to a 404 is bad UX, but even if the page existed, the user never asked for a language change

**Comment by gemanepa** [comment]
Ok the issue is here in line 5 and 6
![Screenshot from 2021-04-18 03-07-41](https://user-images.githubusercontent.com/36349751/115136086-b9529b00-9ff3-11eb-9b11-01ce0d5a8f67.png)

My browser is in english and yet my navigator.language is es-US so yeah, I think this redirect should be removed
![Screenshot from 2021-04-18 03-15-52](https://user-images.githubusercontent.com/36349751/115136177-6c22f900-9ff4-11eb-8436-0c2f32cb9105.png)

**Comment by MartinMinkov** [comment]
Fixed with this commit to only show English docs for now:
https://github.com/MinaProtocol/docs/commit/98546831b528efd26a5fd6cbb7929b482f9a9e4a

Thanks for raising this!
