### ISSUE TITLE
Whitepaper docs are missing

### ISSUE THREAD

**Issue by foogunlana** [MinaProtocol/docs#14]
On this page: https://docs.minaprotocol.com/en try clicking the whitepaper links. They are missing

- https://minaprotocol.com/static/pdf/technicalWhitepaper.pdf - 404 not found, nginx
- https://minaprotocol.com/static/pdf/economicsWhitepaper.pdf - 404 not found, nginx

**Comment by MartinMinkov** [comment]
Link addresses are up here:

https://docs.minaprotocol.com/static/pdf/technicalWhitepaper.pdf
https://docs.minaprotocol.com/static/pdf/economicsWhitepaper.pdf
