### ISSUE TITLE
Fee excess link

### ISSUE THREAD

**Issue by mkoppanen** [MinaProtocol/docs#38]
I was learning more about fees in Mina network and came across this page:

https://docs.minaprotocol.com/en/architecture/lifecycle-payment-technical

In the part with "Fees are handled out-of-band see the fee excess system" there is a link to: https://docs.minaprotocol.com/en/architecture/lifecycle-payment-technical#fee-excess

which seems to go nowhere.

**Comment by jasongitmail** [comment]
Thanks for mentioning this! I'll remove the broken link since this section doesn't exist in that draft document currently. We'll be updating and refactoring these docs and will look into if & where such a section should be re-added.
