### ISSUE TITLE
typo in economicsWhitepaper.pdf

### ISSUE THREAD

**Issue by eric2777** [MinaProtocol/docs#39]
Hello, hopefully I won't disturb anything by posting this issue.
While reading the economics white paper available from for the website, in noticed a type on page 7, paragraph Nomenclature and Denomination.
From the micromina, 1^-6 (equal to 1) should be replaced by 10^-6 (aqual to 0.000001)

<img width="970" alt="Screenshot 2021-05-29 at 19 51 11" src="https://user-images.githubusercontent.com/76942169/120080049-5b67a780-c0b7-11eb-85f8-67fdc0327704.png">

**Comment by jasongitmail** [comment]
Thanks. Will pass this along.
